const PERMISSIONS = {
  TRANSACTION_READ: 'transaction:read',
  TRANSACTION_CREATE: 'transaction:create',
  TRANSACTION_UPDATE: 'transaction:update',
  TRANSACTION_DELETE: 'transaction:delete',
  DASHBOARD_BASIC: 'dashboard:basic',
  DASHBOARD_FULL: 'dashboard:full',
  USER_MANAGE: 'user:manage',
};

const ROLE_PERMISSIONS = {
  viewer: [PERMISSIONS.TRANSACTION_READ, PERMISSIONS.DASHBOARD_BASIC],
  analyst: [
    PERMISSIONS.TRANSACTION_READ,
    PERMISSIONS.DASHBOARD_BASIC,
    PERMISSIONS.DASHBOARD_FULL,
  ],
  admin: [
    PERMISSIONS.TRANSACTION_READ,
    PERMISSIONS.TRANSACTION_CREATE,
    PERMISSIONS.TRANSACTION_UPDATE,
    PERMISSIONS.TRANSACTION_DELETE,
    PERMISSIONS.DASHBOARD_BASIC,
    PERMISSIONS.DASHBOARD_FULL,
    PERMISSIONS.USER_MANAGE,
  ],
};

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS,
};
